r"""Generate a Windows Sandbox config that verifies a build on a clean machine.

The existing PolyShield_Sandbox.wsb is a *development* sandbox: it maps the
whole source tree, a portable Python and a pip cache, then opens Explorer so a
person can work in there. That is the opposite of what a release check needs.

This one maps only the built artifacts, deliberately maps **no Python**, and
runs tools/sandbox_verify.ps1 unattended. The point is a machine with none of
the four things a checkout quietly supplies: an interpreter, developer
environment variables, a source tree, and an existing data root.

    kicomav_env\Scripts\python.exe tools\make_sandbox_wsb.py
    start artifacts\PolyShield_Verify.wsb

Results land in the mapped results folder, which is the only writable mapping,
because everything else in the sandbox is discarded when it closes.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path
from xml.sax.saxutils import escape

ROOT = Path(__file__).resolve().parents[1]


def build(dist: Path, results: Path, skip_service: bool) -> str:
    verify = ROOT / "tools" / "sandbox_verify.ps1"
    for p in (dist, verify):
        if not p.exists():
            sys.exit(f"missing: {p}")
    results.mkdir(parents=True, exist_ok=True)

    args = "-DistDir C:\\PolyShield_dist -ResultsDir C:\\PolyShield_results"
    if skip_service:
        args += " -SkipService"

    # -NoExit keeps the window up so a watching human sees the same result the
    # JSON records. The sandbox is discarded either way.
    command = escape(
        'powershell.exe -NoExit -ExecutionPolicy Bypass -File '
        'C:\\PolyShield_tools\\sandbox_verify.ps1 ' + args
    )

    return f"""<?xml version="1.0" encoding="utf-8"?>
<Configuration>
  <!-- Generated by tools/make_sandbox_wsb.py - do not edit by hand. -->
  <Vgpu>Enable</Vgpu>
  <!-- Networking stays ON: an offline sandbox would make an engine that fails
       to reach its feed look like an engine that is broken. -->
  <Networking>Enable</Networking>
  <ClipboardRedirection>Enable</ClipboardRedirection>
  <AudioInput>Disable</AudioInput>
  <VideoInput>Disable</VideoInput>
  <PrinterRedirection>Disable</PrinterRedirection>
  <MappedFolders>
    <MappedFolder>
      <HostFolder>{escape(str(dist))}</HostFolder>
      <SandboxFolder>C:\\PolyShield_dist</SandboxFolder>
      <ReadOnly>true</ReadOnly>
    </MappedFolder>
    <MappedFolder>
      <HostFolder>{escape(str(ROOT / "tools"))}</HostFolder>
      <SandboxFolder>C:\\PolyShield_tools</SandboxFolder>
      <ReadOnly>true</ReadOnly>
    </MappedFolder>
    <!-- The only writable mapping, and the only reason any of this survives
         the sandbox closing. -->
    <MappedFolder>
      <HostFolder>{escape(str(results))}</HostFolder>
      <SandboxFolder>C:\\PolyShield_results</SandboxFolder>
      <ReadOnly>false</ReadOnly>
    </MappedFolder>
  </MappedFolders>
  <LogonCommand>
    <Command>{command}</Command>
  </LogonCommand>
</Configuration>
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--dist", type=Path, default=ROOT / "dist")
    ap.add_argument("--results", type=Path, default=ROOT / "artifacts" / "sandbox")
    ap.add_argument("--out", type=Path,
                    default=ROOT / "artifacts" / "PolyShield_Verify.wsb")
    ap.add_argument("--skip-service", action="store_true",
                    help="check only the compiled GUI half")
    a = ap.parse_args()

    a.out.parent.mkdir(parents=True, exist_ok=True)
    a.out.write_text(build(a.dist.resolve(), a.results.resolve(), a.skip_service),
                     encoding="utf-8")
    print(f"wrote {a.out}")
    print(f"results will appear in {a.results.resolve()}")
    print(f"\n  start \"\" \"{a.out}\"")
    return 0


if __name__ == "__main__":
    sys.exit(main())
